/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShellAccountsRouteImport } from './routes/_shell.accounts'
import { Route as ShellCardsRouteImport } from './routes/_shell.cards'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellDepositRouteImport } from './routes/_shell.deposit'
import { Route as ShellGoalsRouteImport } from './routes/_shell.goals'
import { Route as ShellInsightsRouteImport } from './routes/_shell.insights'
import { Route as ShellNotificationsRouteImport } from './routes/_shell.notifications'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellStatementsRouteImport } from './routes/_shell.statements'
import { Route as ShellTransactionsRouteImport } from './routes/_shell.transactions'
import { Route as ShellTransfersRouteImport } from './routes/_shell.transfers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAccountsRoute = ShellAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCardsRoute = ShellCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDepositRoute = ShellDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGoalsRoute = ShellGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInsightsRoute = ShellInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStatementsRoute = ShellStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTransactionsRoute = ShellTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTransfersRoute = ShellTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/accounts': typeof ShellAccountsRoute
  '/cards': typeof ShellCardsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/deposit': typeof ShellDepositRoute
  '/goals': typeof ShellGoalsRoute
  '/insights': typeof ShellInsightsRoute
  '/notifications': typeof ShellNotificationsRoute
  '/settings': typeof ShellSettingsRoute
  '/statements': typeof ShellStatementsRoute
  '/transactions': typeof ShellTransactionsRoute
  '/transfers': typeof ShellTransfersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/accounts': typeof ShellAccountsRoute
  '/cards': typeof ShellCardsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/deposit': typeof ShellDepositRoute
  '/goals': typeof ShellGoalsRoute
  '/insights': typeof ShellInsightsRoute
  '/notifications': typeof ShellNotificationsRoute
  '/settings': typeof ShellSettingsRoute
  '/statements': typeof ShellStatementsRoute
  '/transactions': typeof ShellTransactionsRoute
  '/transfers': typeof ShellTransfersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/signup': typeof SignupRoute
  '/_shell/accounts': typeof ShellAccountsRoute
  '/_shell/cards': typeof ShellCardsRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/deposit': typeof ShellDepositRoute
  '/_shell/goals': typeof ShellGoalsRoute
  '/_shell/insights': typeof ShellInsightsRoute
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/statements': typeof ShellStatementsRoute
  '/_shell/transactions': typeof ShellTransactionsRoute
  '/_shell/transfers': typeof ShellTransfersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signup'
    | '/accounts'
    | '/cards'
    | '/dashboard'
    | '/deposit'
    | '/goals'
    | '/insights'
    | '/notifications'
    | '/settings'
    | '/statements'
    | '/transactions'
    | '/transfers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/accounts'
    | '/cards'
    | '/dashboard'
    | '/deposit'
    | '/goals'
    | '/insights'
    | '/notifications'
    | '/settings'
    | '/statements'
    | '/transactions'
    | '/transfers'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/signup'
    | '/_shell/accounts'
    | '/_shell/cards'
    | '/_shell/dashboard'
    | '/_shell/deposit'
    | '/_shell/goals'
    | '/_shell/insights'
    | '/_shell/notifications'
    | '/_shell/settings'
    | '/_shell/statements'
    | '/_shell/transactions'
    | '/_shell/transfers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/accounts': {
      id: '/_shell/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof ShellAccountsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cards': {
      id: '/_shell/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof ShellCardsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/deposit': {
      id: '/_shell/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof ShellDepositRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/goals': {
      id: '/_shell/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof ShellGoalsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/insights': {
      id: '/_shell/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof ShellInsightsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/statements': {
      id: '/_shell/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof ShellStatementsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/transactions': {
      id: '/_shell/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof ShellTransactionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/transfers': {
      id: '/_shell/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof ShellTransfersRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAccountsRoute: typeof ShellAccountsRoute
  ShellCardsRoute: typeof ShellCardsRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellDepositRoute: typeof ShellDepositRoute
  ShellGoalsRoute: typeof ShellGoalsRoute
  ShellInsightsRoute: typeof ShellInsightsRoute
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellStatementsRoute: typeof ShellStatementsRoute
  ShellTransactionsRoute: typeof ShellTransactionsRoute
  ShellTransfersRoute: typeof ShellTransfersRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAccountsRoute: ShellAccountsRoute,
  ShellCardsRoute: ShellCardsRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellDepositRoute: ShellDepositRoute,
  ShellGoalsRoute: ShellGoalsRoute,
  ShellInsightsRoute: ShellInsightsRoute,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellStatementsRoute: ShellStatementsRoute,
  ShellTransactionsRoute: ShellTransactionsRoute,
  ShellTransfersRoute: ShellTransfersRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
